"""Paths to the synthetic fixture set (``fixtures/synthetic/``).

Invented Australian-animal documents in the shapes real government releases
take, generated by ``fixtures/synthetic/generate.py`` and committed, so every
test that needs a real file runs on a bare checkout.
"""

from pathlib import Path

SYNTHETIC_DIR = Path(__file__).resolve().parent.parent / "fixtures" / "synthetic"
DOCUMENTS_DIR = SYNTHETIC_DIR / "documents"
SPREADSHEETS_DIR = SYNTHETIC_DIR / "spreadsheets"

BUDGET_DOCX = DOCUMENTS_DIR / "wombat-portfolio-budget-statements.docx"
NOTICE_PDF = DOCUMENTS_DIR / "quokka-care-decision-notice_redacted.pdf"
AUDIT_PDF = DOCUMENTS_DIR / "koala-habitat-audit.pdf"
AUDIT_TRANSCRIPT = DOCUMENTS_DIR / "koala-habitat-audit_transcript.txt"
FOI_INDEX_PDF = DOCUMENTS_DIR / "bilby-foi-documents-index.pdf"
SCHEDULE_PDF = DOCUMENTS_DIR / "bilby-schedule-of-documents.pdf"
REGISTER_CSV = SPREADSHEETS_DIR / "platypus-sightings-register.csv"
STATISTICS_XLSX = SPREADSHEETS_DIR / "echidna-population-statistics.xlsx"
