"""Report generators for accuracy benchmarks.

Consumed by test_fixture_accuracy.py and test_womblex_collection_accuracy.py —
not a test module itself.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

FIXTURES = Path(__file__).resolve().parent.parent / "fixtures" / "fixtures"
_SUPPORTED_ENTITIES = ["PERSON", "ADDRESS"]
_SUPPORTED_TYPES = set(_SUPPORTED_ENTITIES)


def generate_redaction_report(data: dict) -> str:
    lines: list[str] = [
        "# Redaction Handling Accuracy",
        "",
        "Generated by `test_womblex_collection_accuracy.py`.",
        "",
        f"**Date:** {date.today().isoformat()}",
        "**Detector:** `RedactionDetector` (CV2 contour-based, threshold=50, "
        "min_area=0.1%, max_area=90%)",
        "**Upstream:** Extraction via pluggable strategies; "
        "redaction runs post-extraction as a separate `redact_tag()` operation",
        "",
        "## Throsby",
        "",
    ]

    gt_count = data.get("gt_count", "?")
    detected = data.get("detected", "?")
    affected_gt = data.get("affected_pages_gt", [])
    affected_det = data.get("affected_pages_detected", [])
    gt_pages = len(affected_gt) if affected_gt else "?"
    det_pages = len(affected_det) if affected_det else "?"
    page_recall = (
        f"{len(affected_det)}/{gt_pages} pages"
        if isinstance(gt_pages, int) and isinstance(det_pages, int)
        else "?"
    )

    lines += [
        "### Detection Results",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| GT `<REDACTED>` tags | {gt_count} |",
        f"| Detected regions | {detected} |",
        f"| Affected pages (GT) | {', '.join(str(p) for p in affected_gt) or '?'} |",
        f"| Affected pages (detected) | {', '.join(str(p) for p in affected_det) or '?'} |",
        f"| Page-level recall | {page_recall} |",
        "",
    ]

    per_page = data.get("per_page", {})
    if per_page:
        lines.append("### Per-Page Detections")
        lines.append("")
        for page_num, regions in sorted(per_page.items()):
            lines.append(f"**Page {page_num}** — {len(regions)} region(s):")
            lines.append("")
            lines.append("| # | Bbox (px) | Area (px) |")
            lines.append("|---|-----------|-----------|")
            for i, r in enumerate(regions, 1):
                lines.append(f"| {i} | {r['bbox']} | {r['area_px']:,} |")
            lines.append("")

    blackout = data.get("blackout_pages", "?")
    total = data.get("total_pages", "?")
    ann = data.get("annotation_warnings", "?")

    lines += [
        "### Pipeline Integration",
        "",
        "| Mode | Behaviour | Result |",
        "|------|-----------|--------|",
        f"| `flag` | Adds redaction warning annotations | {ann} warning(s) added |",
        f"| `blackout` | Prepends `[REDACTED]` to affected page text | {blackout}/{total} pages tagged |",
        "| `delete` | Clears affected page text | Not tested (destructive) |",
        "",
    ]
    return "\n".join(lines)


def _pii_scan_table(
    heading: str,
    description: str,
    results: list[dict],
    name_key: str = "name",
    dataset_key: str | None = None,
) -> list[str]:
    lines: list[str] = [f"## {heading}", "", description, ""]
    if not results:
        lines.append("*No results collected.*")
        lines.append("")
        return lines
    entity_names = sorted({e for r in results for e in r.get("tag_counts", {})})
    ent_headers = " | ".join(f"{e}" for e in entity_names)
    ent_sep = " | ".join("---" for _ in entity_names)
    ds_col = "| Dataset " if dataset_key else ""
    ds_sep = "|---" if dataset_key else ""
    lines.append(f"{ds_col}| Document | Words | {ent_headers} | Total |")
    lines.append(f"{ds_sep}|----------|-------| {ent_sep} |-------|")
    for r in results:
        tc = r.get("tag_counts", {})
        ent_vals = " | ".join(str(tc.get(e, 0)) for e in entity_names)
        ds_val = f"| {r[dataset_key]} " if dataset_key else ""
        lines.append(
            f"{ds_val}| `{r[name_key]}` | {r['extracted_words']} "
            f"| {ent_vals} | {r['total_replacements']} |"
        )
    totals = {e: sum(r.get("tag_counts", {}).get(e, 0) for r in results) for e in entity_names}
    totals_str = " | ".join(f"**{totals[e]}**" for e in entity_names)
    ds_total = "| " if dataset_key else ""
    lines.append(f"{ds_total}| **Total** | | {totals_str} | |")
    lines.append("")
    return lines


def generate_pii_report(
    pii_data: dict,
    womblex_pii: list[dict],
    cross_fixture_pii: list[dict],
) -> str:
    model = pii_data.get("model", "all-MiniLM-L6-v2")
    threshold = pii_data.get("threshold", 0.35)

    lines: list[str] = [
        "# PII Cleaning Accuracy",
        "",
        "Generated by `test_womblex_collection_accuracy.py`.",
        "",
        f"**Date:** {date.today().isoformat()}",
        f"**Model:** `{model}`",
        f"**Similarity threshold:** {threshold}",
        "**Supported entities:** PERSON, ADDRESS "
        "(regex + context validation; enrichment graph at post_enrichment)",
        "**Upstream:** Extraction via pluggable strategies "
        "(`strategies_native`, `strategies_scanned`, `strategies_file`, `spreadsheet`); "
        "PII runs post-extraction on `ExtractionResult.full_text`",
        "",
    ]

    # --- Throsby GT section ---
    tag_counts: dict = pii_data.get("tag_counts", {})
    total_entities = pii_data.get(
        "total_entities", sum(tag_counts.values()) if tag_counts else "?",
    )
    supported_entities = pii_data.get("supported_entities", "?")
    coverage = pii_data.get("coverage", None)
    coverage_str = f"{coverage*100:.1f}%" if coverage is not None else "?"

    lines += [
        "## Throsby (Ground Truth)",
        "",
        "### Ground Truth Entity Inventory",
        "",
        "| Entity Type | Count | Supported |",
        "|-------------|-------|-----------|",
    ]
    for tag, count in sorted(tag_counts.items(), key=lambda x: -x[1]):
        supported = "**Yes**" if tag in _SUPPORTED_TYPES else "No"
        lines.append(f"| {tag} | {count} | {supported} |")
    lines += [
        f"| **Total** | **{total_entities}** | **{supported_entities} ({coverage_str})** |",
        "",
    ]

    entity_results: dict = pii_data.get("entity_results", {})
    for entity in _SUPPORTED_ENTITIES:
        er = entity_results.get(entity, {})
        gt_spans = er.get("gt_spans", [])
        found = er.get("found", [])
        missed = er.get("missed", [])
        recall = er.get("recall")
        precision = er.get("precision")
        pred_count = er.get("pred_count", "?")
        fp_count = (pred_count - len(found)) if isinstance(pred_count, int) else "?"
        recall_str = f"{recall*100:.1f}%" if recall is not None else "not run"
        precision_str = f"{precision*100:.1f}%" if precision is not None else "not run"

        lines += [
            f"### {entity} Detection Results",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| GT {entity} count | {len(gt_spans)} |",
            f"| Found | {len(found)} ({', '.join(found) or '—'}) |",
            f"| Missed | {len(missed)} ({', '.join(missed) or '—'}) |",
            f"| **Recall** | **{recall_str}** |",
            f"| Total `<{entity}>` tags produced | {pred_count} |",
            f"| True positives | {len(found)} |",
            f"| False positives | {fp_count} |",
            f"| **Precision** | **{precision_str}** |",
            "",
        ]

    lines += [
        "### Entity Type Coverage",
        "",
        "| Entity Type | GT Count | Supported |",
        "|-------------|----------|-----------|",
    ]
    for tag, count in sorted(tag_counts.items(), key=lambda x: -x[1]):
        supported = "**Yes**" if tag in _SUPPORTED_TYPES else "No"
        lines.append(f"| {tag} | {count} | {supported} |")
    lines.append("")

    # --- Womblex-collection PII scan ---
    lines += _pii_scan_table(
        "Womblex-Collection PII Scan (Regex Only)",
        "Production-representative documents processed with regex-based PII detection.",
        womblex_pii, name_key="name",
    )

    # --- Enrichment additive ---
    isaacus_dir = FIXTURES / "isaacus"
    lines += ["## Enrichment-Enhanced PII (Additive)", ""]
    if isaacus_dir.exists():
        lines.append("*Enrichment fixtures found — results pending implementation.*")
    else:
        lines.append(
            "*Isaacus enrichment fixtures not available. "
            "When `fixtures/isaacus/` is populated, this section will show "
            "additional entities found by the enrichment graph on top of regex.*"
        )
    lines.append("")

    # --- Benchmark-dataset PII scan ---
    lines += _pii_scan_table(
        "Benchmark-Dataset PII Scan (OCR Images, No Ground Truth)",
        "Image fixtures processed via OCR then PII detection.",
        cross_fixture_pii, name_key="stem", dataset_key="dataset",
    )

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Extraction accuracy report
# ---------------------------------------------------------------------------


def generate_extraction_report(results: dict[str, list[dict]]) -> str:
    """Build EXTRACTION.md content from accumulated benchmark results.

    *results* keys: funsd_raw, funsd_preprocessed, iam, doclaynet_raw,
    doclaynet_preprocessed, womblex.
    """
    lines: list[str] = []

    lines.append("# Extraction Accuracy Report")
    lines.append("")
    lines.append("Generated by `test_fixture_accuracy.py`.")
    lines.append("")
    lines.append(f"**Date:** {date.today().isoformat()}")
    lines.append("**Engine:** rapidocr-onnxruntime (PaddleOCR v4 ONNX)")
    lines.append("**Layout:** YOLOv8n (COCO) via ultralytics")
    lines.append("**Architecture:** Pluggable backend protocols (`ingest/interfaces/`); "
                 "strategies split by document family")
    lines.append("")

    # --- Strategy matrix ---
    lines.append("## Extraction Strategy Matrix")
    lines.append("")
    lines.append("Each document type routes to a dedicated strategy via `get_extractor()`. "
                 "Strategies are organised into focused modules to maintain the 750-line file cap.")
    lines.append("")
    lines.append("| Document Type | Strategy | Module | Method |")
    lines.append("|---------------|----------|--------|--------|")
    lines.append("| NATIVE_NARRATIVE | `NativeNarrativeExtractor` | `strategies_native` | PyMuPDF text layer |")
    lines.append("| NATIVE_WITH_STRUCTURED | `NativeWithStructuredExtractor` | `strategies_native` | Text layer + tables/forms/images |")
    lines.append("| STRUCTURED | `StructuredExtractor` | `strategies_native` | Table-focused text layer |")
    lines.append("| SCANNED_MACHINEWRITTEN | `ScannedMachinewrittenExtractor` | `strategies_scanned` | PaddleOCR + YOLO layout |")
    lines.append("| SCANNED_HANDWRITTEN | `ScannedHandwrittenExtractor` | `strategies_scanned` | PaddleOCR (no table detection) |")
    lines.append("| SCANNED_MIXED | `ScannedMixedExtractor` | `strategies_scanned` | PaddleOCR + contour classification |")
    lines.append("| HYBRID | `HybridExtractor` | `strategies_scanned` | Page-level native/OCR routing |")
    lines.append("| IMAGE | `ImageExtractor` | `strategies_scanned` | Direct PaddleOCR |")
    lines.append("| DOCX | `DocxExtractor` | `strategies_file` | python-docx paragraphs + tables |")
    lines.append("| SPREADSHEET | `SpreadsheetExtractor` | `spreadsheet` | pandas per-row/per-sheet |")
    lines.append("| TEXT | `TextExtractor` | `strategies_file` | UTF-8/Latin-1 passthrough |")
    lines.append("")

    # --- Backend protocols ---
    lines.append("### Backend Protocols")
    lines.append("")
    lines.append("OCR, layout analysis, and preprocessing are accessed via typed protocols "
                 "defined in `ingest/interfaces/protocols.py`.")
    lines.append("")
    lines.append("| Protocol | Default Implementation | Notes |")
    lines.append("|----------|----------------------|-------|")
    lines.append("| `OCRReader` | `PaddleOCRReader` (rapidocr-onnxruntime) | Lazy-loaded, cached per lang |")
    lines.append("| `LayoutAnalyzer` | `YOLOLayoutAnalyzer` (yolov8n.pt COCO) | 0 doc-layout predictions; needs replacement |")
    lines.append("| `Preprocessor` | `preprocess_for_ocr()` | Deskew + histogram-gated binarisation |")
    lines.append("")

    def _avg(key: str, data: list) -> float:
        return sum(r[key] for r in data) / len(data) if data else 0.0

    # --- FUNSD ---
    lines.append("## FUNSD — Form OCR")
    lines.append("")

    funsd_raw = results.get("funsd_raw", [])
    funsd_pp = results.get("funsd_preprocessed", [])
    if funsd_raw:
        lines.append("| File | GT Words | CER (raw) | CER (pp) | CER-s (raw) | CER-s (pp) | WER (raw) | WER (pp) | Conf (raw) | Conf (pp) | Steps |")
        lines.append("|------|----------|-----------|----------|-------------|------------|-----------|----------|------------|-----------|-------|")
        for raw, pp in zip(funsd_raw, funsd_pp):
            lines.append(
                f"| `{raw['file']}` | {raw['gt_words']} "
                f"| {raw['cer']:.3f} | {pp['cer']:.3f} "
                f"| {raw['cer_sorted']:.3f} | {pp['cer_sorted']:.3f} "
                f"| {raw['wer']:.3f} | {pp['wer']:.3f} "
                f"| {raw['avg_confidence']:.2f} | {pp['avg_confidence']:.2f} "
                f"| {'+'.join(pp.get('steps', []))} |"
            )
        lines.append(
            f"| **Average** | "
            f"| **{_avg('cer', funsd_raw):.3f}** | **{_avg('cer', funsd_pp):.3f}** "
            f"| **{_avg('cer_sorted', funsd_raw):.3f}** | **{_avg('cer_sorted', funsd_pp):.3f}** "
            f"| **{_avg('wer', funsd_raw):.3f}** | **{_avg('wer', funsd_pp):.3f}** "
            f"| **{_avg('avg_confidence', funsd_raw):.2f}** | **{_avg('avg_confidence', funsd_pp):.2f}** | |"
        )
    else:
        lines.append("*No FUNSD results collected.*")
    lines.append("")

    # --- IAM ---
    lines.append("## IAM — Handwriting OCR")
    lines.append("")

    iam = results.get("iam", [])
    if iam:
        lines.append("| File | GT Words | CER | WER | Avg Confidence | Ground Truth | Prediction |")
        lines.append("|------|----------|-----|-----|----------------|-------------|------------|")
        for r in iam:
            gt_short = r["gt_text"][:40] + ("..." if len(r["gt_text"]) > 40 else "")
            pred_short = r["pred_text"][:40] + ("..." if len(r["pred_text"]) > 40 else "")
            lines.append(
                f"| `{r['file']}` | {r['gt_words']} "
                f"| {r['cer']:.3f} | {r['wer']:.3f} | {r['avg_confidence']:.2f} "
                f"| {gt_short} | {pred_short} |"
            )
        lines.append(
            f"| **Average** | | **{_avg('cer', iam):.3f}** | **{_avg('wer', iam):.3f}** "
            f"| **{_avg('avg_confidence', iam):.2f}** | | |"
        )
    else:
        lines.append("*No IAM results collected.*")
    lines.append("")

    # --- DocLayNet ---
    lines.append("## DocLayNet — Layout Analysis")
    lines.append("")

    dln_raw = results.get("doclaynet_raw", [])
    dln_pp = results.get("doclaynet_preprocessed", [])
    if dln_raw:
        lines.append("| File | GT Blocks | Pred | Precision | Recall | F1 | CER (raw) | CER (pp) | WER (raw) | WER (pp) | Steps |")
        lines.append("|------|----------|------|-----------|--------|-----|-----------|----------|-----------|----------|-------|")
        for raw, pp in zip(dln_raw, dln_pp):
            lines.append(
                f"| `{raw['file']}` | {raw['gt_blocks']} | {raw['pred_layout_regions']} "
                f"| {raw['precision']:.1%} | {raw['recall']:.1%} | {raw['f1']:.1%} "
                f"| {raw['cer']:.3f} | {pp['cer']:.3f} "
                f"| {raw['wer']:.3f} | {pp['wer']:.3f} "
                f"| {'+'.join(pp.get('steps', []))} |"
            )
        lines.append(
            f"| **Average** | | "
            f"| **{_avg('precision', dln_raw):.1%}** | **{_avg('recall', dln_raw):.1%}** | **{_avg('f1', dln_raw):.1%}** "
            f"| **{_avg('cer', dln_raw):.3f}** | **{_avg('cer', dln_pp):.3f}** "
            f"| **{_avg('wer', dln_raw):.3f}** | **{_avg('wer', dln_pp):.3f}** | |"
        )

        # Per-class P/R/F1
        lines.append("")
        lines.append("### Per-Class Layout Detection")
        lines.append("")
        agg_class: dict[str, dict[str, int]] = {}
        for r in dln_raw:
            for lbl, cnts in r["per_class"].items():
                if lbl not in agg_class:
                    agg_class[lbl] = {"tp": 0, "fp": 0, "fn": 0}
                agg_class[lbl]["tp"] += cnts["tp"]
                agg_class[lbl]["fp"] += cnts["fp"]
                agg_class[lbl]["fn"] += cnts["fn"]
        lines.append("| Label | TP | FP | FN | Precision | Recall | F1 |")
        lines.append("|-------|----|----|-----|-----------|--------|-----|")
        for lbl in sorted(agg_class, key=lambda x: -(agg_class[x]["tp"] + agg_class[x]["fn"])):
            c = agg_class[lbl]
            p = c["tp"] / (c["tp"] + c["fp"]) if (c["tp"] + c["fp"]) else 0.0
            rc = c["tp"] / (c["tp"] + c["fn"]) if (c["tp"] + c["fn"]) else 0.0
            f = 2 * p * rc / (p + rc) if (p + rc) else 0.0
            lines.append(f"| {lbl} | {c['tp']} | {c['fp']} | {c['fn']} | {p:.1%} | {rc:.1%} | {f:.1%} |")
    else:
        lines.append("*No DocLayNet results collected.*")
    lines.append("")

    # --- Womblex-collection ---
    lines.append("## Womblex-Collection — Extraction Fidelity")
    lines.append("")

    womblex = results.get("womblex", [])
    if womblex:
        lines.append("| Fixture | Doc Type | Pages (eval/total) | CER | WER | Extracted Chars | GT Chars |")
        lines.append("|---------|----------|--------------------|-----|-----|-----------------|----------|")
        for r in womblex:
            total = r.get("total_pages", r["pages"])
            page_str = f"{r['pages']}/{total}" if total != r["pages"] else str(r["pages"])
            lines.append(
                f"| `{r['name']}` | {r['doc_type']} | {page_str} "
                f"| {r['cer']:.3f} | {r['wer']:.3f} "
                f"| {r['extracted_chars']:,} | {r['gt_chars']:,} |"
            )
        if len(womblex) > 1:
            lines.append(
                f"| **Average** | | | **{_avg('cer', womblex):.3f}** | **{_avg('wer', womblex):.3f}** | | |"
            )
    else:
        lines.append("*No womblex-collection results collected.*")
    lines.append("")

    # --- DOCX / Spreadsheet formats ---
    lines.append("### DOCX")
    lines.append("")
    lines.append("| Fixture | Strategy | Module | Notes |")
    lines.append("|---------|----------|--------|-------|")
    lines.append("| `dfat-corporate-plan-2025-26` | `DocxExtractor` | `strategies_file` | "
                 "python-docx; heading detection via style; no OCR |")
    lines.append("")
    lines.append("DOCX extraction produces a single text block from paragraphs; "
                 "no character-level ground truth exists. Evaluation is structural "
                 "(paragraph count, table detection, heading classification).")
    lines.append("")

    lines.append("### Spreadsheet (CSV / XLSX)")
    lines.append("")
    lines.append("| Fixture | Format | Strategy | Extraction Results | Notes |")
    lines.append("|---------|--------|----------|-------------------|-------|")
    lines.append("| `Approved-providers-au-export` | CSV | `SpreadsheetExtractor` | "
                 "1 per row (10,859) | Key-value pairs per row |")
    lines.append("| `mso-statistics-sept-qtr-2025` | XLSX | `SpreadsheetExtractor` | "
                 "1 per sheet (34) | Mixed narrative + tabular |")
    lines.append("")
    lines.append("Spreadsheet extraction produces one `ExtractionResult` per data row (CSV) "
                 "or per sheet (XLSX). No OCR involved. Evaluation is structural: "
                 "row count preservation, header detection, sheet classification.")
    lines.append("")

    # --- Preprocessing pipeline ---
    lines.append("## Preprocessing Pipeline")
    lines.append("")
    lines.append("All OCR-dependent strategies run images through `preprocess_for_ocr()` "
                 "before PaddleOCR:")
    lines.append("")
    lines.append("| Step | Condition | Effect on FUNSD CER-s |")
    lines.append("|------|-----------|-----------------------|")
    lines.append("| Deskew | Skew angle > 0.5 deg, confidence > 0.3 | Neutral |")
    lines.append("| Otsu binarise | `is_scanned` AND `is_bimodal` | +39% regression |")
    lines.append("| Adaptive binarise | `is_scanned` AND NOT `is_bimodal` | Not observed in fixtures |")
    lines.append("| Binarise skipped | NOT `is_scanned` AND `dynamic_range` > 0.1 | Baseline (best) |")
    lines.append("")

    # --- Metric definitions ---
    lines.append("## Metric Definitions")
    lines.append("")
    lines.append("- **(raw)** = PaddleOCR on original image; **(pp)** = after preprocessing (deskew + binarise).")
    lines.append("- **CER**: Levenshtein distance / reference length. 0.0 = perfect.")
    lines.append("- **CER-s**: GT and OCR words spatially sorted by bounding-box centroid before CER. Isolates recognition from reading-order.")
    lines.append("- **WER**: Word-level Levenshtein / reference word count.")
    lines.append("- **Precision**: Predicted layout blocks matching a GT block with correct label (IoU >= 0.3).")
    lines.append("- **Recall**: GT layout blocks matched by a prediction with correct label (IoU >= 0.3).")
    lines.append("- **F1**: Harmonic mean of precision and recall.")
    lines.append("- **Avg Confidence**: Mean per-region OCR confidence from RapidOCR (0\u20131).")
    lines.append("")

    return "\n".join(lines)
