"""Report generators for accuracy benchmarks.

Consumed by test_womblex_collection_accuracy.py — not a test module itself.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

FIXTURES = Path(__file__).resolve().parent.parent / "fixtures" / "fixtures"
_SUPPORTED_ENTITIES = ["PERSON", "ADDRESS"]
_SUPPORTED_TYPES = set(_SUPPORTED_ENTITIES)


def generate_redaction_report(data: dict) -> str:
    lines: list[str] = [
        "# Redaction Handling Accuracy",
        "",
        "Generated by `test_womblex_collection_accuracy.py`.",
        "",
        f"**Date:** {date.today().isoformat()}",
        "**Detector:** `RedactionDetector` (CV2 contour-based, threshold=50, "
        "min_area=0.1%, max_area=90%)",
        "",
        "## Throsby",
        "",
    ]

    gt_count = data.get("gt_count", "?")
    detected = data.get("detected", "?")
    affected_gt = data.get("affected_pages_gt", [])
    affected_det = data.get("affected_pages_detected", [])
    gt_pages = len(affected_gt) if affected_gt else "?"
    det_pages = len(affected_det) if affected_det else "?"
    page_recall = (
        f"{len(affected_det)}/{gt_pages} pages"
        if isinstance(gt_pages, int) and isinstance(det_pages, int)
        else "?"
    )

    lines += [
        "### Detection Results",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| GT `<REDACTED>` tags | {gt_count} |",
        f"| Detected regions | {detected} |",
        f"| Affected pages (GT) | {', '.join(str(p) for p in affected_gt) or '?'} |",
        f"| Affected pages (detected) | {', '.join(str(p) for p in affected_det) or '?'} |",
        f"| Page-level recall | {page_recall} |",
        "",
    ]

    per_page = data.get("per_page", {})
    if per_page:
        lines.append("### Per-Page Detections")
        lines.append("")
        for page_num, regions in sorted(per_page.items()):
            lines.append(f"**Page {page_num}** — {len(regions)} region(s):")
            lines.append("")
            lines.append("| # | Bbox (px) | Area (px) |")
            lines.append("|---|-----------|-----------|")
            for i, r in enumerate(regions, 1):
                lines.append(f"| {i} | {r['bbox']} | {r['area_px']:,} |")
            lines.append("")

    blackout = data.get("blackout_pages", "?")
    total = data.get("total_pages", "?")
    ann = data.get("annotation_warnings", "?")

    lines += [
        "### Pipeline Integration",
        "",
        "| Mode | Behaviour | Result |",
        "|------|-----------|--------|",
        f"| `flag` | Adds redaction warning annotations | {ann} warning(s) added |",
        f"| `blackout` | Prepends `[REDACTED]` to affected page text | {blackout}/{total} pages tagged |",
        "| `delete` | Clears affected page text | Not tested (destructive) |",
        "",
    ]
    return "\n".join(lines)


def _pii_scan_table(
    heading: str,
    description: str,
    results: list[dict],
    name_key: str = "name",
    dataset_key: str | None = None,
) -> list[str]:
    lines: list[str] = [f"## {heading}", "", description, ""]
    if not results:
        lines.append("*No results collected.*")
        lines.append("")
        return lines
    entity_names = sorted({e for r in results for e in r.get("tag_counts", {})})
    ent_headers = " | ".join(f"{e}" for e in entity_names)
    ent_sep = " | ".join("---" for _ in entity_names)
    ds_col = "| Dataset " if dataset_key else ""
    ds_sep = "|---" if dataset_key else ""
    lines.append(f"{ds_col}| Document | Words | {ent_headers} | Total |")
    lines.append(f"{ds_sep}|----------|-------| {ent_sep} |-------|")
    for r in results:
        tc = r.get("tag_counts", {})
        ent_vals = " | ".join(str(tc.get(e, 0)) for e in entity_names)
        ds_val = f"| {r[dataset_key]} " if dataset_key else ""
        lines.append(
            f"{ds_val}| `{r[name_key]}` | {r['extracted_words']} "
            f"| {ent_vals} | {r['total_replacements']} |"
        )
    totals = {e: sum(r.get("tag_counts", {}).get(e, 0) for r in results) for e in entity_names}
    totals_str = " | ".join(f"**{totals[e]}**" for e in entity_names)
    ds_total = "| " if dataset_key else ""
    lines.append(f"{ds_total}| **Total** | | {totals_str} | |")
    lines.append("")
    return lines


def generate_pii_report(
    pii_data: dict,
    womblex_pii: list[dict],
    cross_fixture_pii: list[dict],
) -> str:
    model = pii_data.get("model", "all-MiniLM-L6-v2")
    threshold = pii_data.get("threshold", 0.35)

    lines: list[str] = [
        "# PII Cleaning Accuracy",
        "",
        "Generated by `test_womblex_collection_accuracy.py`.",
        "",
        f"**Date:** {date.today().isoformat()}",
        f"**Model:** `{model}`",
        f"**Similarity threshold:** {threshold}",
        "**Supported entities:** PERSON, ADDRESS "
        "(regex + context validation; enrichment graph at post_enrichment)",
        "",
    ]

    # --- Throsby GT section ---
    tag_counts: dict = pii_data.get("tag_counts", {})
    total_entities = pii_data.get(
        "total_entities", sum(tag_counts.values()) if tag_counts else "?",
    )
    supported_entities = pii_data.get("supported_entities", "?")
    coverage = pii_data.get("coverage", None)
    coverage_str = f"{coverage*100:.1f}%" if coverage is not None else "?"

    lines += [
        "## Throsby (Ground Truth)",
        "",
        "### Ground Truth Entity Inventory",
        "",
        "| Entity Type | Count | Supported |",
        "|-------------|-------|-----------|",
    ]
    for tag, count in sorted(tag_counts.items(), key=lambda x: -x[1]):
        supported = "**Yes**" if tag in _SUPPORTED_TYPES else "No"
        lines.append(f"| {tag} | {count} | {supported} |")
    lines += [
        f"| **Total** | **{total_entities}** | **{supported_entities} ({coverage_str})** |",
        "",
    ]

    entity_results: dict = pii_data.get("entity_results", {})
    for entity in _SUPPORTED_ENTITIES:
        er = entity_results.get(entity, {})
        gt_spans = er.get("gt_spans", [])
        found = er.get("found", [])
        missed = er.get("missed", [])
        recall = er.get("recall")
        precision = er.get("precision")
        pred_count = er.get("pred_count", "?")
        fp_count = (pred_count - len(found)) if isinstance(pred_count, int) else "?"
        recall_str = f"{recall*100:.1f}%" if recall is not None else "not run"
        precision_str = f"{precision*100:.1f}%" if precision is not None else "not run"

        lines += [
            f"### {entity} Detection Results",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| GT {entity} count | {len(gt_spans)} |",
            f"| Found | {len(found)} ({', '.join(found) or '—'}) |",
            f"| Missed | {len(missed)} ({', '.join(missed) or '—'}) |",
            f"| **Recall** | **{recall_str}** |",
            f"| Total `<{entity}>` tags produced | {pred_count} |",
            f"| True positives | {len(found)} |",
            f"| False positives | {fp_count} |",
            f"| **Precision** | **{precision_str}** |",
            "",
        ]

    lines += [
        "### Entity Type Coverage",
        "",
        "| Entity Type | GT Count | Supported |",
        "|-------------|----------|-----------|",
    ]
    for tag, count in sorted(tag_counts.items(), key=lambda x: -x[1]):
        supported = "**Yes**" if tag in _SUPPORTED_TYPES else "No"
        lines.append(f"| {tag} | {count} | {supported} |")
    lines.append("")

    # --- Womblex-collection PII scan ---
    lines += _pii_scan_table(
        "Womblex-Collection PII Scan (Regex Only)",
        "Production-representative documents processed with regex-based PII detection.",
        womblex_pii, name_key="name",
    )

    # --- Enrichment additive ---
    isaacus_dir = FIXTURES / "isaacus"
    lines += ["## Enrichment-Enhanced PII (Additive)", ""]
    if isaacus_dir.exists():
        lines.append("*Enrichment fixtures found — results pending implementation.*")
    else:
        lines.append(
            "*Isaacus enrichment fixtures not available. "
            "When `fixtures/isaacus/` is populated, this section will show "
            "additional entities found by the enrichment graph on top of regex.*"
        )
    lines.append("")

    # --- Benchmark-dataset PII scan ---
    lines += _pii_scan_table(
        "Benchmark-Dataset PII Scan (OCR Images, No Ground Truth)",
        "Image fixtures processed via OCR then PII detection.",
        cross_fixture_pii, name_key="stem", dataset_key="dataset",
    )

    return "\n".join(lines)
