"""Money accuracy against the corpus's typed ground-truth transcripts.

Scores `find_money` over every `*_transcript-with-money-tags.txt` in the
fixtures set and writes `docs/accuracy/MONEY.md`. Fixture-gated: the tagged
transcripts live in the external fixtures repo, so a bare checkout skips.

The report rendering lives here rather than in `accuracy_reports.py` — that
module is at its line budget, and this report needs no shared state.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

import pytest

from womblex.process.money import MoneyOptions, find_money
from womblex.utils.money_metrics import (
    MoneyScore,
    parse_tagged_transcript,
    score_money,
)

FIXTURES = Path(__file__).resolve().parent.parent / "fixtures" / "fixtures"
DOCS = Path(__file__).resolve().parent.parent / "docs" / "accuracy"

_TAGGED = sorted(FIXTURES.glob("womblex-collection/**/*_transcript-with-money-tags.txt"))

pytestmark = pytest.mark.skipif(
    not _TAGGED, reason="no money-tagged transcripts in the fixtures set"
)


def _plain_for(tagged: Path) -> Path:
    return tagged.with_name(tagged.name.replace("-with-money-tags.txt", ".txt"))


@pytest.mark.parametrize("tagged", _TAGGED, ids=lambda p: p.stem[:40])
def test_tagged_transcript_is_only_tags_from_its_transcript(tagged: Path):
    """Ground-truth integrity gate (MONEY-LABELLING.md §7.1).

    Strip the tags and the result must be the transcript byte for byte. A
    labeller who edited the prose has corrupted the fixture, and every number
    scored against it after that is fiction.
    """
    plain = _plain_for(tagged)
    if not plain.exists():
        pytest.skip(f"no sibling transcript for {tagged.name}")
    stripped, figures = parse_tagged_transcript(tagged.read_text(encoding="utf-8"))
    assert stripped == plain.read_text(encoding="utf-8")
    assert figures, "a tagged transcript with no tags is not ground truth"


@pytest.mark.benchmark
def test_money_accuracy_against_ground_truth():
    """Recall / precision / scale accuracy over the tagged transcripts.

    Gated on the **narrative** figures only. A bare cell whose money-ness comes
    from its column header is the column path's to find (`money_columns.py`),
    and the transcript flattens tables to markdown rows where no header reaches
    the cell — so table figures are measured and reported, not asserted on.
    """
    scores: dict[str, MoneyScore] = {}

    for tagged in _TAGGED:
        plain = _plain_for(tagged)
        if not plain.exists():
            continue
        text, figures = parse_tagged_transcript(tagged.read_text(encoding="utf-8"))
        spans = find_money(text, MoneyOptions())
        scores[tagged.stem] = score_money(figures, spans)

    if not scores:
        pytest.skip("no tagged transcript had a sibling transcript")

    DOCS.mkdir(parents=True, exist_ok=True)
    (DOCS / "MONEY.md").write_text(_render(scores), encoding="utf-8")

    for name, score in scores.items():
        narrative_gt = score.gt_money - sum(1 for m in score.misses if m.locus == "table")
        narrative_hits = narrative_gt - sum(1 for m in score.misses if m.locus == "narrative")
        assert narrative_hits / narrative_gt >= 0.95, f"{name}: narrative recall"
        assert score.precision >= 0.95, f"{name}: precision"
        assert not score.scale_errors, f"{name}: {score.scale_errors}"
        assert not [w for _, w in score.false_positives if w == "percent"], (
            f"{name}: a percentage was read as an amount"
        )


def _render(scores: dict[str, MoneyScore]) -> str:
    lines = [
        "# Money Extraction Accuracy",
        "",
        "Generated by `test_money_accuracy.py` — do not edit by hand.",
        "",
        f"**Date:** {datetime.now(UTC).date().isoformat()}",
        "**Ground truth:** typed tags wrapped in place in the document's own "
        "transcript (`MONEY-LABELLING.md`). Stripping the tags reproduces the "
        "transcript byte for byte.",
        "**Detector:** `find_money` at default `MoneyOptions` "
        "(`implicit_context` off) over the reassembled transcript.",
        "",
        "Recall is split by locus. A **narrative** figure carries its own "
        "evidence and is `find_money`'s to find; a **table** figure is a bare "
        "cell under a money header, which `money_columns.classify_column` "
        "resolves from the column — not visible in a flattened transcript, so "
        "it is reported here, not gated.",
        "",
        "| Document | Narrative recall | Table recall | Precision | Scale accuracy | % read as $ |",
        "|---|---|---|---|---|---|",
    ]

    for name, s in scores.items():
        tbl_miss = sum(1 for m in s.misses if m.locus == "table")
        narr_miss = sum(1 for m in s.misses if m.locus == "narrative")
        narr_gt = s.gt_money - tbl_miss
        pct_fp = sum(1 for _, w in s.false_positives if w == "percent")
        lines.append(
            f"| {name[:44]} | {narr_gt - narr_miss}/{narr_gt} "
            f"({(narr_gt - narr_miss) / narr_gt:.1%}) | {tbl_miss} unseen | "
            f"{s.precision:.1%} | {s.scale_accuracy:.1%} "
            f"({len(s.scale_errors)} error(s)) | {pct_fp} |"
        )

    lines += ["", "## Misses", ""]
    for name, s in scores.items():
        lines.append(f"### {name}")
        lines.append("")
        if not s.misses:
            lines += ["None.", ""]
            continue
        lines += ["| Figure | Tag | Locus |", "|---|---|---|"]
        lines += [f"| `{m.text}` | {m.kind} | {m.locus} |" for m in s.misses]
        lines.append("")

    return "\n".join(lines) + "\n"
